# fly.toml app configuration file generated for comfyui-deploy-backend on 2024-07-30T11:55:33+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'comfyui-deploy-backend'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
