# fly.toml app configuration file generated for punitd-modal-comfyui-deploy on 2024-07-30T11:36:54+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'punitd-modal-comfyui-deploy'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
